AWSTemplateFormatVersion: "2010-09-09"

Description: "CloudFormation template for deployment of shared infrastructure for Customer360.
              deploys the following components:
              - VPC and its components
              - MySQL Database
              - Change Data Capture to S3"

Parameters: 
  # Network - VPC Resource Parameters
  BaseVpcStackName:
    Description: A name for vpc that will be prefixed to resource names
    Type: String
    Default: vpc-customer360

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.14.16.0/20
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/8-24

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.14.16.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/8-24 
  
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.14.19.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/8-24
  
  # Storage - MySQL Resource Parameters  
  DBMasterUser:
    Type: String
    Description : The database admin account username
    MinLength: 1
    MaxLength: 16
    Default: admin
    AllowedPattern: '([a-zA-Z0-9\-]){1,16}'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBInstanceClass:
    Type: String
    Default: db.t2.small
    AllowedValues:
    - db.t2.small
    - db.t2.medium
    - db.t2.large
      
  DBSnapshotId:
    Type: String
    Default: 'arn:aws:rds:eu-west-1:271342081496:snapshot:rds:clouderaprep-2019-02-16-23-53'
  
  DBMultiAZ:
    Type: String
    Default: false
    AllowedValues: 
    - true
    - false

  DBAllocatedStorage:
    Type: String
    Default: 20
    AllowedPattern: '([0-9]){2,4}'
    ConstraintDescription: must be an integer (20GB-16TB).
  
  # Tags Parameters
  IsWork:
    Type: String  
    Description: Defines if it is work related activity
    AllowedValues: [true, false]
    Default: true

  WorkType:
    Type: String  
    Description: Defines the type of work being done
    Default: customer360

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:

    - Label:
        default: Network - VPC Resource Parameters
      Parameters:
      - BaseVpcStackName
      - VpcCIDR
      - PublicSubnet1CIDR
      - PrivateSubnet1CIDR
    
    - Label:
        default: Storage - MySQL Resource Parameters
      Parameters:
      - DBMasterUser
      - DBInstanceClass
      - DBSnapshotId
      - DBMultiAZ
      - DBAllocatedStorage

    - Label:
        default: Tags
      Parameters:
      - IsWork
      - WorkType
    
    ParameterLabels:
      BaseVpcStackName:
        default: VPC Name
      VpcCIDR:
        default: VPC CIDR
      PublicSubnet1CIDR:
        default: public-1a
      PrivateSubnet1CIDR:
        default: private-1a
      DBMasterUser:
        default: Admin User for MySQL Database
      DBInstanceClass:
        default: Instance Type for MySQL Database
      DBSnapshotId:
        default: Snapshot ID
      DBMultiAZ:
        default: Multi AZ option
      DBAllocatedStorage:
        default: Storage for MySQL Database
      IsWork:
        default: Work Related Stack?
      WorkType:
        default: If Work Related, What Project/Training/Type

Mappings:
  SourceCode:
    General:
      S3Bucket: "eabootcamp-customer360-2019"
      KeyPrefix: "customer360"

Resources:
  Customer360NetworkStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["/", ["https://s3.amazonaws.com", !FindInMap ["SourceCode", "General", "S3Bucket"], !FindInMap ["SourceCode", "General", "KeyPrefix"], "customer360-network.yml"]]
      Parameters:
        BaseVpcStackName: !Ref BaseVpcStackName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        IsWork: !Ref IsWork
        WorkType: !Ref WorkType
  
  Customer360StorageStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["/", ["https://s3.amazonaws.com", !FindInMap ["SourceCode", "General", "S3Bucket"], !FindInMap ["SourceCode", "General", "KeyPrefix"], "customer360-storage.yml"]]
      Parameters:
        BaseVpcStackName: !Ref BaseVpcStackName
        DBInstanceClass: !Ref DBInstanceClass
        DBSnapshotId: !Ref DBSnapshotId
        DBMultiAZ: !Ref DBMultiAZ
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBMasterUser: !Ref DBMasterUser
        IsWork: !Ref IsWork
        WorkType: !Ref WorkType
    DependsOn:
    - Customer360NetworkStack

Outputs:
  StackName:
    Value:
      Ref: AWS::StackName
  RegionName:
    Value:
      Ref: AWS::Region