AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Master Customer360 CloudFormation template.
  It deploys:
    - Infrastructure per the customer360 Reference Architecture Diagram 
      (S3 bucket path goes here)
    - VPC network with 3 public subnets and internet gateway
    - MySQL 5.6 RDS database using provided snapshot with port 3306 
      publicly accessible and ParameterGroup for DMS compatibility 
    - Roles for DMS -> dms-vpc-role, dms-cloudwatch-logs-role
    - Change Data Capture needed infrastructure. Replication Instance for DMS
      and DMS MySQL endpoint

Parameters: 
  EnvironmentName:
    Description: A name for vpc that will be prefixed to resource names
    Type: String
    Default: vpc-customer360

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.14.16.0/20
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/8-24

  PublicSubnet1Cidr:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.14.16.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/8-24 
  
  PublicSubnet2Cidr:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.14.17.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/8-24 
  
  PublicSubnet3Cidr:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the third Availability Zone
    Type: String
    Default: 10.14.18.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/8-24 
  
  # Storage - MySQL Resource Parameters  
  DBMasterUser:
    Type: String
    Description : The database admin account username
    MinLength: 1
    MaxLength: 16
    Default: username
    AllowedPattern: '([a-zA-Z0-9\-]){1,16}'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBInstanceClass:
    Type: String
    Default: db.t2.small
    AllowedValues:
    - db.t2.small
    - db.t2.medium
    - db.t2.large
      
  DBSnapshotId:
    Type: String
    Default: 'arn:aws:rds:eu-west-1:271342081496:snapshot:clouderaprep-final-snapshot'
  
  DBMultiAZ:
    Type: String
    Default: false
    AllowedValues: 
    - true
    - false

  DBAllocatedStorage:
    Type: String
    Default: 20
    AllowedPattern: '([0-9]){2,4}'
    ConstraintDescription: must be an integer (20GB-16TB).
  
  # IAM - Access related Parameters
  ExistsRoles:
    Default: N
    Description: If the roles exists for this workshop, please enter Y, else enter N
    Type: String
    MinLength: '1'
    MaxLength: '1'
    AllowedPattern: "[YN]"
    ConstraintDescription: Permitted value is Y or N.

  # CDC - Database Migration Services Parameters
  DMSReplicationInstance:
    Default: dms.t2.small
    AllowedValues:
      - dms.t2.micro
      - dms.t2.small
      - dms.t2.medium
      - dms.t2.large
      - dms.c4.large
      - dms.c4.xlarge
      - dms.c4.2xlarge
      - dms.c4.4xlarge
    Description: The instance type to use for the replication instance.
    Type: String

  # Tags Parameters
  IsWork:
    Type: String  
    Description: Defines if it is work related activity
    AllowedValues: [true, false]
    Default: true

  WorkType:
    Type: String  
    Description: Defines the type of work being done
    Default: customer360

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:

    - Label:
        default: Network - VPC Resource Parameters
      Parameters:
      - BaseVpcStackName
      - VpcCIDR
      - PublicSubnet1Cidr
      - PublicSubnet2Cidr
      - PublicSubnet3Cidr
    
    - Label:
        default: Storage - MySQL Resource Parameters
      Parameters:
      - DBMasterUser
      - DBInstanceClass
      - DBSnapshotId
      - DBMultiAZ
      - DBAllocatedStorage
    
    - Label:
        default: CDC - Database Migration Services Parameters
      Parameters:
      - DMSReplicationInstance

    - Label:
        default: IAM - Access related Parameters
      Parameters:
      - ExistsRoles

    - Label:
        default: Tags
      Parameters:
      - IsWork
      - WorkType
    
    ParameterLabels:
      BaseVpcStackName:
        default: VPC Name
      VpcCIDR:
        default: VPC CIDR
      PublicSubnet1Cidr:
        default: CIDR for Public Subnet 1
      PublicSubnet2Cidr:
        default: CIDR for Public Subnet 2
      PublicSubnet3Cidr:
        default: CIDR for Public Subnet 3
      DBMasterUser:
        default: Admin User for MySQL Database
      DBInstanceClass:
        default: Instance Type for MySQL Database
      DBSnapshotId:
        default: Snapshot ID
      DBMultiAZ:
        default: Multi AZ option
      DBAllocatedStorage:
        default: Storage for MySQL Database
      DMSReplicationInstance:
        default: DMS Instance Type
      ExistsRoles:
        default: Y or N if DMS Cloudwatch Role exists
      IsWork:
        default: Work Related Stack?
      WorkType:
        default: If Work Related, What Project/Training/Type

Mappings:
  SourceCode:
    General:
      S3Bucket: "eabootcamp-customer360-2019"
      KeyPrefix: "customer360"

Resources:
  Customer360NetworkStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["/", ["https://s3.amazonaws.com", !FindInMap ["SourceCode", "General", "S3Bucket"], !FindInMap ["SourceCode", "General", "KeyPrefix"], "customer360-network.yml"]]
      Parameters:
        BaseVpcStackName: !Ref BaseVpcStackName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PublicSubnet3Cidr: !Ref PublicSubnet3Cidr
        IsWork: !Ref IsWork
        WorkType: !Ref WorkType
  
  Customer360MySQLStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["/", ["https://s3.amazonaws.com", !FindInMap ["SourceCode", "General", "S3Bucket"], !FindInMap ["SourceCode", "General", "KeyPrefix"], "customer360-mysql.yml"]]
      Parameters:
        BaseVpcStackName: !Ref BaseVpcStackName
        DBInstanceClass: !Ref DBInstanceClass
        DBSnapshotId: !Ref DBSnapshotId
        DBMultiAZ: !Ref DBMultiAZ
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBMasterUser: !Ref DBMasterUser
        IsWork: !Ref IsWork
        WorkType: !Ref WorkType
    DependsOn:
    - Customer360NetworkStack

  Customer360RolesStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["/", ["https://s3.amazonaws.com", !FindInMap ["SourceCode", "General", "S3Bucket"], !FindInMap ["SourceCode", "General", "KeyPrefix"], "customer360-roles.yml"]]
      Parameters:
        BaseVpcStackName: !Ref BaseVpcStackName
        ExistsDMSVPCRole: !Ref ExistsRoles
        ExistsDMSCloudwatchRole: !Ref ExistsRoles
        IsWork: !Ref IsWork
        WorkType: !Ref WorkType
  
  Customer360DMSStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["/", ["https://s3.amazonaws.com", !FindInMap ["SourceCode", "General", "S3Bucket"], !FindInMap ["SourceCode", "General", "KeyPrefix"], "customer360-dms.yml"]]
      Parameters:
        BaseVpcStackName: !Ref BaseVpcStackName
        ReplicationInstance: !Ref DMSReplicationInstance
        IsWork: !Ref IsWork
        WorkType: !Ref WorkType
    DependsOn:
    - Customer360NetworkStack
    - Customer360MySQLStack
        

Outputs:
  StackName:
    Value:
      Ref: AWS::StackName
  RegionName:
    Value:
      Ref: AWS::Region